quotes:
  data:
    - Keep away from people who try to belittle your ambitions. Small people always do that, but the really great make you feel that you, too, can become great.
    - Every adversity, every failure, every heartache carries with it the seed of an equal or greater benefit.
    - Success in life is not for those who run fast, but for those who keep running and always on the move.
    - If roses were not special weeds would not envy them.
    - Wisdom from a stranger is better than ignorance from a friend.
